# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MemoryLeakDemo' do
    pod 'SwiftTask'
    pod 'XCGLogger'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'ObjectMapper'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'MBProgressHUD'
end

target 'MemoryLeakDemoTests' do
    pod 'FBSnapshotTestCase'
end

target 'MemoryLeakDemoUITests' do

end

