# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SSHUD' do
pod 'SnapKit'
end

target 'SSHUDTests' do

end

target 'SSHUDUITests' do

end

